#!/usr/bin/env bash
set -euo pipefail

# Provision a Mac from dotfiles + 1Password.
# Usage: ./install.sh [company]
#   company — name of a 1Password vault (default: personal)
#
# All 1Password items are optional (processed when they exist in $COMPANY vault):
#   "Git Config"     — fields: email, signing_key → ~/.gitconfig-github
#   "GitHub"         — fields: token → gh auth login
#   "Shell Secrets"  — any env var fields → ~/.config/secrets/$COMPANY.zsh
#   "GitLab Config"  — fields: signing_key → ~/.gitconfig-gitlab
#   "AWS Platform Dev"    — fields: access_key_id, secret_access_key
#   "AWS Data Dev"   — fields: access_key_id, secret_access_key
#   "AWS Datadesk"   — fields: access_key_id, secret_access_key
#   "NPM Config"     — fields: scoped_registry, registry_host → ~/.npmrc
#   "Claude Code"    — fields: api_key → appended to secrets file + installs claude

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPANY="${1:-personal}"

# ── colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[install]${NC} $*"; }
warn()    { echo -e "${YELLOW}[install]${NC} $*"; }
error()   { echo -e "${RED}[install]${NC} $*" >&2; }

# ── helpers ────────────────────────────────────────────────────────────────────
op_item_exists() {
  local vault="$1" item="$2"
  op item get "$item" --vault "$vault" &>/dev/null
}

op_read_field() {
  local vault="$1" item="$2" field="$3"
  op item get "$item" --vault "$vault" --fields label="$field" --reveal 2>/dev/null
}

# ── 1. Homebrew ────────────────────────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
  info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# ── 2. brew bundle ─────────────────────────────────────────────────────────────
info "Running brew bundle..."
brew bundle --file="$DOTFILES_DIR/Brewfile"

# ── 3. dev directories ─────────────────────────────────────────────────────────
info "Creating ~/dev directories..."
mkdir -p ~/dev/personal ~/dev/work

# ── 4. validate 1Password vault ────────────────────────────────────────────────
info "Checking 1Password vault '$COMPANY'..."
if ! op vault get "$COMPANY" &>/dev/null; then
  error "Vault '$COMPANY' not found. Is 1Password CLI signed in?"
  error "Run: op signin"
  exit 1
fi

# ── 5. Git Config (optional) ────────────────────────────────────────────────
if op_item_exists "$COMPANY" "Git Config"; then
  info "Writing ~/.gitconfig-github..."
  GIT_EMAIL="$(op_read_field "$COMPANY" "Git Config" "email")"
  GIT_SIGNING_KEY="$(op_read_field "$COMPANY" "Git Config" "signing_key")"
  cat > ~/.gitconfig-github <<EOF
[user]
	email = ${GIT_EMAIL}
	signingKey = ${GIT_SIGNING_KEY}
EOF
  chmod 600 ~/.gitconfig-github
else
  warn "No 'Git Config' item found in '$COMPANY' vault — skipping"
fi

# ── 6. GitLab Config (optional) ────────────────────────────────────────────────
if op_item_exists "$COMPANY" "GitLab Config"; then
  info "Writing ~/.gitconfig-gitlab..."
  GITLAB_SIGNING_KEY="$(op_read_field "$COMPANY" "GitLab Config" "signing_key")"
  cat > ~/.gitconfig-gitlab <<EOF
[user]
	signingKey = ${GITLAB_SIGNING_KEY}
EOF
  chmod 600 ~/.gitconfig-gitlab
else
  warn "No 'GitLab Config' item found in '$COMPANY' vault — skipping"
fi

# ── 7. Shell Secrets (optional) ────────────────────────────────────────────────
SECRETS_DIR=~/.config/secrets
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

if op_item_exists "$COMPANY" "Shell Secrets"; then
  info "Writing $SECRETS_DIR/$COMPANY.zsh..."
  SECRETS_FILE="$SECRETS_DIR/$COMPANY.zsh"

  # Read all fields via JSON and emit export lines, skipping 1Password metadata fields
  op item get "Shell Secrets" --vault "$COMPANY" --format json --reveal \
    | python3 - <<'PYEOF' > "$SECRETS_FILE"
import json, sys

data = json.load(sys.stdin)
SKIP_LABELS = {"notesPlain", "password", "username", "hostname", "port", "database", "url"}

print("# Auto-generated by install.sh — do not edit manually")
for field in data.get("fields", []):
    label = field.get("label", "")
    value = field.get("value", "")
    if not label or not value:
        continue
    if label in SKIP_LABELS:
        continue
    # Escape single quotes in value
    escaped = value.replace("'", "'\\''")
    print(f"export {label}='{escaped}'")
PYEOF

  chmod 600 "$SECRETS_FILE"
else
  warn "No 'Shell Secrets' item found in '$COMPANY' vault — skipping"
fi

# ── 8. AWS credentials (optional) ──────────────────────────────────────────────
AWS_ITEMS=("AWS Platform Dev" "AWS Data Dev" "AWS Datadesk")
AWS_PROFILES=("platform-dev" "data-dev" "datadesk")

AWS_CREDS_CONTENT=""
AWS_CONFIG_CONTENT=""

for i in "${!AWS_ITEMS[@]}"; do
  item="${AWS_ITEMS[$i]}"
  profile="${AWS_PROFILES[$i]}"

  if op_item_exists "$COMPANY" "$item"; then
    info "Reading '$item' from '$COMPANY' vault..."
    KEY_ID="$(op_read_field "$COMPANY" "$item" "access_key_id")"
    SECRET="$(op_read_field "$COMPANY" "$item" "secret_access_key")"
    AWS_CREDS_CONTENT+="[${profile}]
aws_access_key_id = ${KEY_ID}
aws_secret_access_key = ${SECRET}

"
    AWS_CONFIG_CONTENT+="[profile ${profile}]
region = us-east-1

"
  fi
done

if [[ -n "$AWS_CREDS_CONTENT" ]]; then
  info "Writing ~/.aws/credentials and ~/.aws/config..."
  mkdir -p ~/.aws
  printf '%s' "$AWS_CREDS_CONTENT" > ~/.aws/credentials
  chmod 600 ~/.aws/credentials
  printf '%s' "$AWS_CONFIG_CONTENT" > ~/.aws/config
  chmod 600 ~/.aws/config
else
  warn "No AWS items found in '$COMPANY' vault — skipping"
fi

# ── 9. NPM Config (optional) ───────────────────────────────────────────────────
if op_item_exists "$COMPANY" "NPM Config"; then
  info "Writing ~/.npmrc..."
  SCOPED_REGISTRY="$(op_read_field "$COMPANY" "NPM Config" "scoped_registry")"
  REGISTRY_HOST="$(op_read_field "$COMPANY" "NPM Config" "registry_host")"
  cat > ~/.npmrc <<EOF
${SCOPED_REGISTRY}:registry=https://${REGISTRY_HOST}/
//${REGISTRY_HOST}/:_authToken=\${GITLAB_NPM_TOKEN}
EOF
  chmod 600 ~/.npmrc
else
  warn "No 'NPM Config' item found in '$COMPANY' vault — skipping"
fi

# ── 10. GitHub auth (optional) ─────────────────────────────────────────────────
if op_item_exists "$COMPANY" "GitHub"; then
  info "Authenticating with GitHub..."
  GH_TOKEN="$(op_read_field "$COMPANY" "GitHub" "token")"
  echo "$GH_TOKEN" | gh auth login --with-token
else
  warn "No 'GitHub' item found in '$COMPANY' vault — skipping gh auth"
fi

# ── 11. Stow dotfile packages ──────────────────────────────────────────────────
info "Stowing dotfile packages..."
cd "$DOTFILES_DIR"
packages=(zsh git starship ghostty mise hammerspoon ssh)
for pkg in "${packages[@]}"; do
  info "  -> $pkg"
  stow --restow "$pkg"
done

# ── 12. mise install ───────────────────────────────────────────────────────────
info "Installing mise runtimes..."
mise install java@temurin-21 node@lts python@3.12

# ── 13. Claude Code (optional) ─────────────────────────────────────────────────
if op_item_exists "$COMPANY" "Claude Code"; then
  info "Installing Claude Code..."
  ANTHROPIC_API_KEY="$(op_read_field "$COMPANY" "Claude Code" "api_key")"

  # Append key to secrets file (create if it doesn't exist)
  SECRETS_FILE="$SECRETS_DIR/$COMPANY.zsh"
  if [[ ! -f "$SECRETS_FILE" ]]; then
    mkdir -p "$SECRETS_DIR"
    chmod 700 "$SECRETS_DIR"
    touch "$SECRETS_FILE"
    chmod 600 "$SECRETS_FILE"
  fi

  # Only append if not already present
  if ! grep -q "ANTHROPIC_API_KEY" "$SECRETS_FILE" 2>/dev/null; then
    echo "export ANTHROPIC_API_KEY='${ANTHROPIC_API_KEY}'" >> "$SECRETS_FILE"
  fi

  npm install -g @anthropic-ai/claude-code
else
  warn "No 'Claude Code' item found in '$COMPANY' vault — skipping"
fi

info "Done! Open a new shell or run: source ~/.zshrc"
