#!/usr/bin/env bash
set -euo pipefail

# Provision a Mac from dotfiles + 1Password.
# Usage: ./install.sh [company]
#   company — name of a 1Password vault (default: personal)
#
# All 1Password items are optional (processed when they exist in $COMPANY vault):
#   "Git Config"     — fields: email, signing_key → ~/.gitconfig-github
#   "GitHub"         — fields: token → gh auth login
#   "Shell Secrets"  — any env var fields → ~/.config/secrets/$COMPANY.zsh
#   "GitLab Config"  — fields: signing_key → ~/.gitconfig-gitlab
#   "Claude Code"    — fields: api_key → appended to secrets file (install always runs)
#
# Company-specific steps: see companies/<slug>.sh

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPANY="${1:-personal}"
COMPANY_SLUG="$(basename "$COMPANY" | tr '[:upper:]' '[:lower:]')"

# ── colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[install]${NC} $*"; }
warn()    { echo -e "${YELLOW}[install]${NC} $*"; }
error()   { echo -e "${RED}[install]${NC} $*" >&2; }

# ── helpers ────────────────────────────────────────────────────────────────────
op_item_exists() {
  local vault="$1" item="$2"
  op item get "$item" --vault "$vault" &>/dev/null
}

op_read_field() {
  local vault="$1" item="$2" field="$3"
  op item get "$item" --vault "$vault" --fields label="$field" --reveal 2>/dev/null
}

# ── 1. Homebrew ────────────────────────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
  info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# ── 2. brew bundle ─────────────────────────────────────────────────────────────
info "Running brew bundle..."
brew bundle --file="$DOTFILES_DIR/Brewfile" || warn "brew bundle had failures — already-installed apps may need sudo to adopt (safe to ignore)"

# ── 3. dev directories ─────────────────────────────────────────────────────────
info "Creating ~/dev directories..."
mkdir -p ~/dev/personal ~/dev/work

# ── 4. validate 1Password vault ────────────────────────────────────────────────
info "Checking 1Password vault '$COMPANY'..."
if ! op vault get "$COMPANY" &>/dev/null; then
  error "Vault '$COMPANY' not found. Is 1Password CLI signed in?"
  error "Run: op signin"
  exit 1
fi

# ── 5. Git Config (optional) ────────────────────────────────────────────────
if op_item_exists "$COMPANY" "Git Config"; then
  info "Writing ~/.gitconfig-github..."
  GIT_EMAIL="$(op_read_field "$COMPANY" "Git Config" "email")"
  GIT_SIGNING_KEY="$(op_read_field "$COMPANY" "Git Config" "signing_key")"
  cat > ~/.gitconfig-github <<EOF
[user]
	email = ${GIT_EMAIL}
	signingKey = ${GIT_SIGNING_KEY}
EOF
  chmod 600 ~/.gitconfig-github
else
  warn "No 'Git Config' item found in '$COMPANY' vault — skipping"
fi

# ── 6. GitLab Config (optional) ────────────────────────────────────────────────
if op_item_exists "$COMPANY" "GitLab Config"; then
  info "Writing ~/.gitconfig-gitlab..."
  GITLAB_SIGNING_KEY="$(op_read_field "$COMPANY" "GitLab Config" "signing_key")"
  cat > ~/.gitconfig-gitlab <<EOF
[user]
	signingKey = ${GITLAB_SIGNING_KEY}
EOF
  chmod 600 ~/.gitconfig-gitlab
else
  warn "No 'GitLab Config' item found in '$COMPANY' vault — skipping"
fi

# ── 7. Shell Secrets (optional) ────────────────────────────────────────────────
SECRETS_DIR=~/.config/secrets
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

if op_item_exists "$COMPANY" "Shell Secrets"; then
  info "Writing $SECRETS_DIR/$COMPANY_SLUG.zsh..."
  SECRETS_FILE="$SECRETS_DIR/$COMPANY_SLUG.zsh"

  # Read all fields via JSON and emit export lines, skipping 1Password metadata fields.
  # Fields with labels starting with "#" are written as commented-out exports —
  # they stay in 1Password for reference but are inactive until manually uncommented.
  #
  # Note: Python script is written to a temp file so the JSON pipe to stdin works
  # correctly (pipe + heredoc conflict makes json.load(sys.stdin) receive nothing).
  _PY_SCRIPT="$(mktemp)"
  cat > "$_PY_SCRIPT" <<'PYEOF'
import json, sys

data = json.load(sys.stdin)
SKIP_LABELS = {"notesPlain", "password", "username", "hostname", "port", "database", "url"}

print("# Auto-generated by install.sh — do not edit manually")
for field in data.get("fields", []):
    label = field.get("label", "")
    value = field.get("value", "")
    if not label or not value:
        continue
    if label in SKIP_LABELS:
        continue
    commented = label.startswith("#")
    clean_label = label.lstrip("#").strip()
    escaped = value.replace("'", "'\\''")
    prefix = "# " if commented else ""
    print(f"{prefix}export {clean_label}='{escaped}'")
PYEOF
  op item get "Shell Secrets" --vault "$COMPANY" --format json --reveal \
    | python3 "$_PY_SCRIPT" > "$SECRETS_FILE"
  rm "$_PY_SCRIPT"

  chmod 600 "$SECRETS_FILE"
else
  warn "No 'Shell Secrets' item found in '$COMPANY' vault — skipping"
fi

# ── 8. GitHub auth (optional) ─────────────────────────────────────────────────
if op_item_exists "$COMPANY" "GitHub"; then
  info "Authenticating with GitHub..."
  GH_TOKEN="$(op_read_field "$COMPANY" "GitHub" "token")"
  echo "$GH_TOKEN" | gh auth login --with-token || warn "GitHub auth failed — token may be expired, update in 1Password and re-run"
else
  warn "No 'GitHub' item found in '$COMPANY' vault — skipping gh auth"
fi

# ── 9. Stow dotfile packages ──────────────────────────────────────────────────
info "Stowing dotfile packages..."
cd "$DOTFILES_DIR"
packages=(zsh git starship ghostty mise hammerspoon ssh)
for pkg in "${packages[@]}"; do
  info "  -> $pkg"
  stow --restow --adopt --target "$HOME" "$pkg"
done

# ── 10. mise install ───────────────────────────────────────────────────────────
info "Installing mise runtimes..."
mise install node@lts python@3.12

# ── 11. Claude Code ────────────────────────────────────────────────────────────
info "Installing Claude Code..."
npm install -g @anthropic-ai/claude-code

# If vault has a "Claude Code" item with api_key, append it to the secrets file
if op_item_exists "$COMPANY" "Claude Code"; then
  ANTHROPIC_API_KEY="$(op_read_field "$COMPANY" "Claude Code" "api_key")"
  SECRETS_FILE="$SECRETS_DIR/$COMPANY_SLUG.zsh"
  if [[ ! -f "$SECRETS_FILE" ]]; then
    mkdir -p "$SECRETS_DIR"
    chmod 700 "$SECRETS_DIR"
    touch "$SECRETS_FILE"
    chmod 600 "$SECRETS_FILE"
  fi
  if ! grep -q "ANTHROPIC_API_KEY" "$SECRETS_FILE" 2>/dev/null; then
    echo "export ANTHROPIC_API_KEY='${ANTHROPIC_API_KEY}'" >> "$SECRETS_FILE"
  fi
fi

# ── 12. Company hook ───────────────────────────────────────────────────────────
COMPANY_SCRIPT="$DOTFILES_DIR/companies/${COMPANY_SLUG}.sh"
if [[ -f "$COMPANY_SCRIPT" ]]; then
  info "Running company script: $COMPANY_SCRIPT"
  # shellcheck source=/dev/null
  source "$COMPANY_SCRIPT"
fi

info "Done! Open a new shell or run: source ~/.zshrc"
